#!/usr/bin/env python3
"""Build the curated literature evidence tables from reviewed primary sources.

The broad OpenAlex pool is intentionally kept separate.  This script only writes
the manually admitted deep-read set and deterministic derivative tables.  It
does not query the network and does not treat discovery metadata as evidence.
"""

from __future__ import annotations

import csv
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
QUERY_DATE = "2026-08-13"


PAPERS = [
    {
        "paper_id": "D01",
        "title": "TD-MPC2: Scalable, Robust World Models for Continuous Control",
        "year": "2024",
        "venue": "ICLR 2024 (Spotlight)",
        "publication_status": "formal_main_track",
        "layer": "general_world_model;multi_step_planning",
        "formal_url": "https://openreview.net/forum?id=Oxh5CstDJU",
        "pdf_url": "https://openreview.net/pdf?id=Oxh5CstDJU",
        "code_url": "https://github.com/nicklashansen/tdmpc2",
        "license": "MIT",
        "stars": "921",
        "motivation": "Make latent world-model control robust and scalable across many continuous-control tasks without task-specific tuning.",
        "state_action": "Vector or image observation encoded to a latent state; continuous action is concatenated into latent dynamics and reward prediction.",
        "prediction_targets": "Next latent state, reward, termination, policy prior, and an ensemble of Q estimates.",
        "training_horizon": "Multi-step latent consistency, reward, termination, and value losses with rho-based temporal weighting.",
        "planning": "MPPI/CEM-like receding-horizon latent planning; mixes policy-prior trajectories with sampled trajectories and adds terminal Q.",
        "uncertainty_safety": "Multiple Q heads use clipped/min or average aggregation, but this is value conservatism rather than a calibrated dynamics ensemble or a traffic safety fallback.",
        "protocol_baselines": "104 continuous-control tasks across four domains; compares model-based and model-free methods including TD-MPC, DreamerV3, and SAC.",
        "result_summary": "The paper reports strong fixed-hyperparameter performance and scaling to a 317M-parameter multi-task agent; these results do not establish discrete TSC performance.",
        "limitation": "The action space and planner are continuous; direct application to heterogeneous discrete phase masks and coupled intersection actions is not established.",
        "traffic_inspiration": "Reuse the loss decomposition and terminal-value pattern, not the continuous MPPI action parameterization.",
        "evidence_pointer": "paper Abstract, Sec. 3-4 and Fig. 1; code tdmpc2/common/world_model.py:26-30,114-215 and tdmpc2/tdmpc2.py:123-203,268-303",
    },
    {
        "paper_id": "D02",
        "title": "Mastering Diverse Control Tasks through World Models (DreamerV3)",
        "year": "2025",
        "venue": "Nature 640",
        "publication_status": "formal_journal",
        "layer": "general_world_model;imagined_policy_learning",
        "formal_url": "https://www.nature.com/articles/s41586-025-08744-2",
        "pdf_url": "https://www.nature.com/articles/s41586-025-08744-2.pdf",
        "code_url": "https://github.com/danijar/dreamerv3",
        "license": "MIT",
        "stars": "3657",
        "motivation": "Build one robust world-model RL algorithm that works across diverse tasks with fixed hyperparameters.",
        "state_action": "Images or vector observations are encoded into recurrent discrete latent states conditioned on previous actions.",
        "prediction_targets": "Observation reconstruction, reward, continuation, latent dynamics; separate actor and distributional critic learn on imagined states.",
        "training_horizon": "Sequence world-model training and imagined actor-critic rollouts with value bootstrapping.",
        "planning": "A learned actor selects actions at execution; the model supplies imagined trajectories for actor and critic training rather than online candidate MPC.",
        "uncertainty_safety": "Robust normalization, free bits, KL balancing, and distributional value prediction; no explicit ensemble disagreement or MaxPressure-style fallback.",
        "protocol_baselines": "More than 150 tasks across eight domains with fixed hyperparameters; the paper includes ablations of model signals and robustness techniques.",
        "result_summary": "The article reports broad fixed-configuration performance and shows that several robustness components matter on subsets of tasks.",
        "limitation": "The full actor-critic system is a large architectural change and provides no direct evidence for CityFlow structured states or discrete joint phase planning.",
        "traffic_inspiration": "Reward/continuation/value heads and sequence training support the multi-step hypothesis; wholesale migration is out of scope.",
        "evidence_pointer": "article Fig. 1, Learning algorithm, World model learning, Critic learning, Evaluation and Fig. 6; code dreamerv3/agent.py:156-244,382-482",
    },
    {
        "paper_id": "D03",
        "title": "Trajectory World Models for Heterogeneous Environments",
        "year": "2025",
        "venue": "ICML 2025",
        "publication_status": "formal_main_track",
        "layer": "general_world_model;heterogeneous_pretraining",
        "formal_url": "https://proceedings.mlr.press/v267/yin25f.html",
        "pdf_url": "https://raw.githubusercontent.com/mlresearch/v267/main/assets/yin25f/yin25f.pdf",
        "code_url": "https://github.com/thuml/TrajWorld",
        "license": "NOASSERTION",
        "stars": "19",
        "motivation": "Pretrain one low-dimensional world model despite different sensor and actuator schemas across environments.",
        "state_action": "Tokenized trajectory variables with observation/action indicators, padding masks, and variable masks.",
        "prediction_targets": "Distributional next observation and reward; environment termination is supplied by task-specific termination functions.",
        "training_horizon": "Autoregressive trajectory training over context windows; pretraining masks variables to support heterogeneous schemas.",
        "planning": "Online MPC evaluates proposed action sequences with the learned trajectory model; policy proposals can seed candidates.",
        "uncertainty_safety": "Distribution entropy, confidence, prediction standard deviation, or kNN distance can penalize reward; these are not all calibrated epistemic uncertainty.",
        "protocol_baselines": "UniTraj contains over one million trajectories from 80 environments; evaluation covers transition prediction, off-policy evaluation, and online MPC.",
        "result_summary": "The official ICML page reports gains in all three evaluation uses, but no traffic-signal environment is included.",
        "limitation": "No repository license is declared and the provided MPC assumes continuous actions and task-specific termination logic.",
        "traffic_inspiration": "Intersection/roadnet masks can play the role of heterogeneous variable indicators; pretraining should be tested only after within-city dynamics is reliable.",
        "evidence_pointer": "paper Abstract and Sec. 3-5; code dynamics/trajworld_dynamics.py:375-515 and mpc/mpc.py:54-126,201-231",
    },
    {
        "paper_id": "D04",
        "title": "Do Transformer World Models Give Better Policy Gradients?",
        "year": "2024",
        "venue": "ICML 2024",
        "publication_status": "formal_main_track",
        "layer": "general_world_model;action_conditioning",
        "formal_url": "https://proceedings.mlr.press/v235/ma24i.html",
        "pdf_url": "https://raw.githubusercontent.com/mlresearch/v235/main/assets/ma24i/ma24i.pdf",
        "code_url": "not_confirmed",
        "license": "not_confirmed",
        "stars": "not_queried",
        "motivation": "Long-horizon policy gradients through common world models can follow circuitous and hard-to-optimize computational paths.",
        "state_action": "Action-conditioned transformer formulations provide direct paths from action sequences to future outcomes.",
        "prediction_targets": "Future outcomes/rewards used for differentiable policy optimization.",
        "training_horizon": "Long-horizon action-conditioned modeling designed around gradient-path structure.",
        "planning": "Differentiable policy-gradient optimization through the action-conditioned model, not discrete candidate enumeration.",
        "uncertainty_safety": "No central calibrated uncertainty or fallback mechanism in the core claim.",
        "protocol_baselines": "Realistic long-horizon control tasks compare transformer world-model variants and policy optimization landscapes.",
        "result_summary": "The paper reports that its action-conditioned models produce easier optimization landscapes and better policies than competitive baselines.",
        "limitation": "Its core benefit concerns backpropagated policy gradients; our current planner ranks discrete candidates without differentiating through actions.",
        "traffic_inspiration": "The useful translation is explicit joint-action-to-future conditioning, not the policy-gradient claim itself.",
        "evidence_pointer": "official PMLR page lines 8-25; paper Sec. 3-5",
    },
    {
        "paper_id": "D05",
        "title": "Deep Reinforcement Learning in a Handful of Trials using Probabilistic Dynamics Models",
        "year": "2018",
        "venue": "NeurIPS 2018",
        "publication_status": "formal_main_track",
        "layer": "uncertainty_mpc;ensemble",
        "formal_url": "https://proceedings.neurips.cc/paper/2018/hash/3de568f8597b94bda53149c7d7f5958c-Abstract.html",
        "pdf_url": "https://proceedings.neurips.cc/paper_files/paper/2018/file/3de568f8597b94bda53149c7d7f5958c-Paper.pdf",
        "code_url": "https://github.com/kchua/handful-of-trials",
        "license": "MIT",
        "stars": "481",
        "motivation": "Improve model-based RL sample efficiency without giving up asymptotic control performance.",
        "state_action": "Continuous states and actions feed probabilistic neural dynamics models.",
        "prediction_targets": "A Gaussian distribution over state changes; bootstrapped ensemble members represent distinct learned dynamics.",
        "training_horizon": "One-step probabilistic models are propagated by trajectory sampling through the planning horizon.",
        "planning": "Cross-entropy method searches action sequences and executes the first action in MPC fashion.",
        "uncertainty_safety": "Aleatoric uncertainty comes from predictive distributions and epistemic uncertainty from ensemble disagreement.",
        "protocol_baselines": "Four continuous-control benchmarks against model-based and model-free baselines; the paper emphasizes interaction count.",
        "result_summary": "The official abstract reports matching model-free asymptotic performance on several tasks with many fewer samples.",
        "limitation": "Continuous CEM and Gaussian state dynamics do not map directly to masked discrete phases, and disagreement must be calibrated before acting as a safety signal.",
        "traffic_inspiration": "Train independently bootstrapped traffic dynamics heads and test whether disagreement predicts candidate ranking error.",
        "evidence_pointer": "paper Abstract, Sec. 4 and Algorithm 1; official NeurIPS reviews describe ensemble plus CEM trajectory sampling",
    },
    {
        "paper_id": "D06",
        "title": "When to Trust Your Model: Model-Based Policy Optimization",
        "year": "2019",
        "venue": "NeurIPS 2019",
        "publication_status": "formal_main_track",
        "layer": "multi_step_planning;model_bias",
        "formal_url": "https://proceedings.neurips.cc/paper/2019/hash/5faf461eff3099671ad63c6f3f094f7f-Abstract.html",
        "pdf_url": "https://proceedings.neurips.cc/paper/2019/file/5faf461eff3099671ad63c6f3f094f7f-Paper.pdf",
        "code_url": "https://github.com/jannerm/mbpo",
        "license": "MIT",
        "stars": "560",
        "motivation": "Balance cheap model-generated data against bias that grows with model rollout length.",
        "state_action": "Continuous states/actions with learned probabilistic dynamics; real replay states seed imagined rollouts.",
        "prediction_targets": "One-step next-state/reward dynamics used to generate short synthetic branches.",
        "training_horizon": "Short model rollouts branch from real data; rollout horizon is a controlled source of bias.",
        "planning": "Uses model data to train a policy rather than performing online candidate MPC.",
        "uncertainty_safety": "The main safeguard is deliberately short model use tied to empirical model generalization, not a deployment fallback.",
        "protocol_baselines": "Continuous-control evaluation compares sample efficiency and asymptotic performance against prior MBRL and model-free methods.",
        "result_summary": "The official abstract reports that short branched rollouts retain gains while avoiding failure at long horizons.",
        "limitation": "It does not show that minimizing one-step MSE improves counterfactual action ranking in discrete traffic control.",
        "traffic_inspiration": "Treat rollout horizon as an ablation and prefer real-state-rooted counterfactual evaluation over unrestricted synthetic trajectories.",
        "evidence_pointer": "paper Abstract, Sec. 3-5 and Algorithm 1",
    },
    {
        "paper_id": "D07",
        "title": "MOPO: Model-based Offline Policy Optimization",
        "year": "2020",
        "venue": "NeurIPS 2020",
        "publication_status": "formal_main_track",
        "layer": "uncertainty_mpc;offline_pessimism",
        "formal_url": "https://proceedings.neurips.cc/paper/2020/hash/a322852ce0df73e204b7e67cbbef0d0a-Abstract.html",
        "pdf_url": "https://proceedings.neurips.cc/paper/2020/file/a322852ce0df73e204b7e67cbbef0d0a-Paper.pdf",
        "code_url": "https://github.com/tianheyu927/mopo",
        "license": "MIT",
        "stars": "191",
        "motivation": "Prevent an offline policy from exploiting learned dynamics outside the logged data distribution.",
        "state_action": "Offline continuous-control transitions train an ensemble probabilistic dynamics model.",
        "prediction_targets": "Next-state/reward distributions and ensemble variance used as an error proxy.",
        "training_horizon": "Synthetic model rollouts augment offline policy learning under a penalized reward.",
        "planning": "Optimizes a policy in an uncertainty-penalized learned MDP.",
        "uncertainty_safety": "Subtracts a model-uncertainty penalty to approximate a lower bound on true return.",
        "protocol_baselines": "D4RL and related-task generalization against offline model-free and model-based baselines.",
        "result_summary": "The official paper reports stronger benchmark and related-task results, but reviews note that the practical Gaussian variance penalty is not identical to the theoretical error term.",
        "limitation": "Ensemble variance can be miscalibrated, and the continuous offline-RL setting differs from near-online CityFlow candidate scoring.",
        "traffic_inspiration": "Use lower-confidence candidate scores only if uncertainty is empirically calibrated against true CityFlow ranking error.",
        "evidence_pointer": "paper Abstract and Sec. 4-5; official NeurIPS reviews/meta-review on variance penalty limitations",
    },
    {
        "paper_id": "D08",
        "title": "COMBO: Conservative Offline Model-Based Policy Optimization",
        "year": "2021",
        "venue": "NeurIPS 2021",
        "publication_status": "formal_main_track",
        "layer": "offline_pessimism;value_regularization",
        "formal_url": "https://proceedings.neurips.cc/paper/2021/hash/f29a179746902e331572c483c45e5086-Abstract.html",
        "pdf_url": "https://proceedings.neurips.cc/paper/2021/file/f29a179746902e331572c483c45e5086-Paper.pdf",
        "code_url": "not_confirmed",
        "license": "not_confirmed",
        "stars": "not_queried",
        "motivation": "Explicit neural-model uncertainty can be inaccurate and cause poor offline model-based RL performance.",
        "state_action": "Offline transitions plus model-generated out-of-support state-action tuples.",
        "prediction_targets": "A learned dynamics model supplies synthetic rollouts; a conservative Q function is regularized on out-of-support tuples.",
        "training_horizon": "Model rollouts generate training data for value learning rather than serving only as an MPC score.",
        "planning": "Policy optimization uses conservative values without requiring explicit uncertainty at decision time.",
        "uncertainty_safety": "Conservatism is imposed in the value function, avoiding reliance on a possibly unreliable uncertainty estimator.",
        "protocol_baselines": "Offline RL benchmarks, related unseen tasks, and image-based control against model-free and model-based baselines.",
        "result_summary": "The paper reports competitive or stronger results and a policy-improvement guarantee under its assumptions.",
        "limitation": "Adding a full offline conservative Q learner is a different project scope from the current planner and is not a minimal first change.",
        "traffic_inspiration": "Keep as a fallback if ensemble calibration fails; do not assume disagreement is automatically trustworthy.",
        "evidence_pointer": "paper Abstract, Sec. 4-5 and Conclusion",
    },
    {
        "paper_id": "D09",
        "title": "MOReL: Model-Based Offline Reinforcement Learning",
        "year": "2020",
        "venue": "NeurIPS 2020",
        "publication_status": "formal_main_track",
        "layer": "offline_pessimism;unknown_state_action",
        "formal_url": "https://proceedings.neurips.cc/paper/2020/hash/f7efa4f864ae9b88d43527f4b14f750f-Abstract.html",
        "pdf_url": "https://proceedings.neurips.cc/paper/2020/file/f7efa4f864ae9b88d43527f4b14f750f-Paper.pdf",
        "code_url": "not_confirmed",
        "license": "not_confirmed",
        "stars": "not_queried",
        "motivation": "Provide a model-based offline RL framework whose learned surrogate discourages unknown state-action regions.",
        "state_action": "Offline continuous-control transitions; an uncertainty detector marks unfamiliar state-action inputs.",
        "prediction_targets": "Dynamics inside a pessimistic MDP plus an absorbing negative-reward state for unknown inputs.",
        "training_horizon": "Policy learning occurs in the pessimistic learned MDP.",
        "planning": "Any near-optimal policy solver can be used in the pessimistic MDP.",
        "uncertainty_safety": "Unknown state-action detection routes risky transitions to a strongly penalized absorbing state.",
        "protocol_baselines": "Standard offline RL benchmarks with theoretical lower-bound analysis and five-seed experiments noted by reviewers.",
        "result_summary": "The official paper reports matching or exceeding contemporary offline RL baselines under its benchmark protocol.",
        "limitation": "A binary unknown detector may be too coarse for traffic candidates that differ by one phase, and threshold sensitivity must be measured.",
        "traffic_inspiration": "A support gate is conceptually closer to MaxPressure fallback than unconstrained model search, but must be defined on trajectory data rather than invented heuristics.",
        "evidence_pointer": "paper Abstract and Sec. 4-5; official NeurIPS reviews on unknown-state-action detector",
    },
    {
        "paper_id": "D10",
        "title": "Optimizing Traffic Control with Model-Based Learning: A Pessimistic Approach to Data-Efficient Policy Inference",
        "year": "2023",
        "venue": "KDD 2023",
        "publication_status": "formal_main_track",
        "layer": "tsc_model_based;offline_pessimism",
        "formal_url": "https://doi.org/10.1145/3580305.3599459",
        "pdf_url": "repository Supporting Document.pdf",
        "code_url": "https://github.com/siddarth-c/KDD23-ADAC",
        "license": "NOASSERTION",
        "stars": "0",
        "motivation": "Learn traffic-signal policies from cheaply collected cyclic-control data while managing offline distribution shift.",
        "state_action": "Traffic state vectors and discrete signal actions from an offline replay buffer.",
        "prediction_targets": "A finite empirical MDP: action-conditioned transition matrices and pessimistically shaped rewards over core states.",
        "training_horizon": "Value iteration solves the inferred MDP; nearest-neighbor transitions connect logged and evaluation states.",
        "planning": "Policy inference uses the solved finite MDP rather than neural multi-step candidate rollout.",
        "uncertainty_safety": "Distance from logged neighbors subtracts a fixed or adaptive cost from reward for OOD states/actions.",
        "protocol_baselines": "A signalized roundabout and a large multi-intersection SUMO environment; offline data are collected from cyclic signal control.",
        "result_summary": "The paper and repository describe data-efficient traffic control with pessimistic costs; exact table values are not reused here because the accessible supporting document protocol differs from our CityFlow setup.",
        "limitation": "The repository has no declared license, uses a non-neural finite MDP, and cannot be copied directly.",
        "traffic_inspiration": "The closest direct evidence for penalizing distance from traffic data support; compare its gate conceptually, not its implementation.",
        "evidence_pointer": "KDD paper Abstract; repo README; ADAC/dac_mdp.py:141-252,285-338,412-502",
    },
    {
        "paper_id": "D11",
        "title": "Boosting Efficiency in Task-Agnostic Exploration through Causal Knowledge",
        "year": "2024",
        "venue": "IJCAI 2024",
        "publication_status": "formal_main_track",
        "layer": "causal_world_model;tsc_case_study",
        "formal_url": "https://www.ijcai.org/proceedings/2024/591",
        "pdf_url": "https://www.ijcai.org/proceedings/2024/0591.pdf",
        "code_url": "https://github.com/CMACH508/CausalExploration",
        "license": "NOASSERTION",
        "stars": "8",
        "motivation": "Collect data that improves task-agnostic world models more efficiently by learning and exploiting causal structure.",
        "state_action": "Factorized state variables plus action; the TSC case study is a single three-lane intersection with switch/stay action.",
        "prediction_targets": "One predictor per next-state factor, with inputs masked by a learned causal graph.",
        "training_horizon": "Online one-step world-model fitting and intrinsic exploration rewards based on prediction error/data usefulness.",
        "planning": "The world model guides exploration; it is not used as a multi-intersection deployment MPC controller.",
        "uncertainty_safety": "Prediction error becomes intrinsic reward; no ensemble, OOD lower bound, or fallback.",
        "protocol_baselines": "Synthetic systems, a single-intersection SUMO task, and MuJoCo tasks.",
        "result_summary": "The IJCAI page reports improved sample efficiency and reliability under its task-agnostic exploration setting.",
        "limitation": "Its TSC experiment has one intersection and binary switch/stay action; causal discovery and prediction error do not prove safe candidate ranking.",
        "traffic_inspiration": "Use known phase-movement topology as a supervised structural prior before attempting causal discovery.",
        "evidence_pointer": "paper Sec. 3-5 and official page; traffic/models/CausalWorldModel.py:9-79",
    },
    {
        "paper_id": "D12",
        "title": "Enhancing Traffic Signal Control through Model-Based Reinforcement Learning and Policy Reuse",
        "year": "2026",
        "venue": "Expert Systems with Applications 298",
        "publication_status": "formal_journal",
        "layer": "tsc_model_based;transfer",
        "formal_url": "https://www.sciencedirect.com/science/article/pii/S0957417425033706",
        "pdf_url": "subscription_or_author_copy",
        "code_url": "https://github.com/RL-DLMU/PRLight-and-PLight",
        "license": "NOASSERTION",
        "stars": "0",
        "motivation": "Reduce retraining when traffic flows or road networks change.",
        "state_action": "Multi-intersection observations with adjacency; discrete actions enter a shared encoder-decoder and Q network.",
        "prediction_targets": "Action-conditioned next observation from a decoder; the encoder is shared with a Q network.",
        "training_horizon": "One-step transition prediction jointly learned with control; PRLight reuses source policies based on source-target similarity.",
        "planning": "Q-network control and policy reuse, not online MPC candidate ranking.",
        "uncertainty_safety": "Similarity-weighted policy selection; no calibrated ensemble or MaxPressure fallback.",
        "protocol_baselines": "Three road-network types and eight flow datasets; within-network flow transfer and cross-network transfer.",
        "result_summary": "The journal page reports faster adaptation and compares joint model-policy learning through ablation.",
        "limitation": "Repository lacks a declared license; the environmental model is used for transfer similarity, not demonstrated conservative planning.",
        "traffic_inspiration": "Reuse action-conditioned decoder and cross-flow protocol ideas; independently test whether similarity helps before heterogeneous pretraining.",
        "evidence_pointer": "journal Abstract/Introduction; PLight/EDQN.py:20-137 and repository data directories",
    },
    {
        "paper_id": "D13",
        "title": "ModelLight: Model-Based Meta-Reinforcement Learning for Traffic Signal Control",
        "year": "2021",
        "venue": "arXiv:2111.08067",
        "publication_status": "preprint",
        "layer": "tsc_model_based;meta_rl",
        "formal_url": "https://arxiv.org/abs/2111.08067",
        "pdf_url": "https://arxiv.org/pdf/2111.08067",
        "code_url": "https://github.com/XingshuaiHuang/ModelLight",
        "license": "MIT",
        "stars": "10",
        "motivation": "Adapt TSC policies to new traffic scenarios with fewer real simulator samples.",
        "state_action": "Single-intersection lane vehicle counts plus an explicit phase vector representing the selected discrete action.",
        "prediction_targets": "Next lane vehicle counts and reward using GP, ANN, or LSTM environment models.",
        "training_horizon": "One-step model fitting followed by recursively generated imaginary transitions for meta-RL updates.",
        "planning": "The model expands training data; execution uses a learned Q policy rather than online MPC.",
        "uncertainty_safety": "No ensemble disagreement, OOD support test, or rule-based fallback in the inspected core path.",
        "protocol_baselines": "Repository provides Hangzhou, Jinan, Atlanta, and Los Angeles scenarios and compares meta-RL/controller variants in the paper.",
        "result_summary": "Because this is an arXiv preprint, it is retained as direct TSC mechanism evidence but not treated as top-venue validation.",
        "limitation": "The action model is local and recursive synthetic data can compound error; the repository uses old TensorFlow/Keras components.",
        "traffic_inspiration": "It directly validates using a phase vector rather than an arbitrary action id, supporting phase-movement semantics.",
        "evidence_pointer": "paper Sec. 3-5; intersection_model.py:21-99,171-216 and metalearner.py:64-169",
    },
    {
        "paper_id": "D14",
        "title": "Image-Based Traffic Signal Control via World Models",
        "year": "2022",
        "venue": "Frontiers of Information Technology & Electronic Engineering 23(12)",
        "publication_status": "formal_journal",
        "layer": "tsc_world_model;image_boundary",
        "formal_url": "https://www.fitee.zjujournals.com/en/article/doi/10.1631/FITEE.2200323/",
        "pdf_url": "official page PDF link",
        "code_url": "not_confirmed",
        "license": "not_confirmed",
        "stars": "not_queried",
        "motivation": "Use predictive traffic representations for proactive rather than purely reactive signal control.",
        "state_action": "Vehicle-position images and signal-control actions at an intersection.",
        "prediction_targets": "Latent/image traffic dynamics and multi-step imagined samples inspired by DreamerV2.",
        "training_horizon": "Multi-step imagined data train a controller; the controller acts directly at execution.",
        "planning": "World-model imagination supports policy optimization rather than executing video MPC online.",
        "uncertainty_safety": "No ensemble calibration or conservative fallback is established on the official page.",
        "protocol_baselines": "The article reports image prediction and TSC performance against common baselines; exact protocol is not comparable to our structured CityFlow state.",
        "result_summary": "The official abstract reports improved control and accurate image prediction in its setting.",
        "limitation": "Its image state, Dreamer-style controller, and likely compute/data requirements are outside the locked structured-state scope.",
        "traffic_inspiration": "Confirms that multi-step world-model imagination has been tried in TSC, so generic 'first World Model for traffic lights' is not a valid gap.",
        "evidence_pointer": "official article page lines 16-90 and full paper",
    },
    {
        "paper_id": "D15",
        "title": "X-Light: Cross-City Traffic Signal Control Using Transformer on Transformer as Meta Multi-Agent Reinforcement Learner",
        "year": "2024",
        "venue": "IJCAI 2024",
        "publication_status": "formal_main_track",
        "layer": "cross_city;multi_agent_tsc",
        "formal_url": "https://www.ijcai.org/proceedings/2024/11",
        "pdf_url": "https://www.ijcai.org/proceedings/2024/0011.pdf",
        "code_url": "not_confirmed",
        "license": "not_confirmed",
        "stars": "not_queried",
        "motivation": "Transfer multi-agent TSC policies across cities rather than retraining each network from scratch.",
        "state_action": "Full MDP trajectories containing local and neighbor states, actions, and rewards.",
        "prediction_targets": "A lower transformer models intra-city neighborhood decision interactions; an upper transformer includes a dynamics prediction objective across scenarios.",
        "training_horizon": "Trajectory-level meta-training across multiple scenarios/cities.",
        "planning": "Learned actor/controller; not a learned environment used to score online candidates.",
        "uncertainty_safety": "No ensemble disagreement or MaxPressure fallback in the central method.",
        "protocol_baselines": "Multi-scenario training and zero-shot unseen-scenario evaluation against meta-RL and TSC baselines.",
        "result_summary": "The official IJCAI page reports +7.91% average zero-shot improvement and up to +16.3% in some cases under its protocol.",
        "limitation": "Its dynamics predictor is a representation/meta-learning auxiliary, not evidence that an MPC world model improves MaxPressure.",
        "traffic_inspiration": "Use full state-action-reward neighborhood trajectories for cross-city pretraining only after action-conditioned dynamics passes within-city tests.",
        "evidence_pointer": "paper Abstract, Sec. 3-5, Fig. 4-7; official IJCAI page",
    },
    {
        "paper_id": "D16",
        "title": "CrossLight: Offline-to-Online Reinforcement Learning for Cross-City Traffic Signal Control",
        "year": "2024",
        "venue": "KDD 2024",
        "publication_status": "formal_main_track",
        "layer": "cross_city;offline_to_online",
        "formal_url": "https://doi.org/10.1145/3637528.3671927",
        "pdf_url": "https://zhoujingbo.github.io/paper/2024CrossLightKDD.pdf",
        "code_url": "not_confirmed",
        "license": "not_confirmed",
        "stars": "not_queried",
        "motivation": "Use source-city offline trajectories to initialize efficient online adaptation in a new city.",
        "state_action": "Traffic decision trajectories with traffic patterns and road-network structures across cities.",
        "prediction_targets": "Pattern-structure-aware trajectory representations and meta-knowledge rather than an explicit next-state MPC dynamics model.",
        "training_horizon": "Offline meta-training followed by online target-city adaptation.",
        "planning": "Policy optimization/adaptation, not candidate trajectory evaluation.",
        "uncertainty_safety": "No central dynamics ensemble or rule-based fallback.",
        "protocol_baselines": "Cross-city offline-to-online transfer against cross-city and offline/online RL baselines.",
        "result_summary": "Formal KDD publication establishes a recent cross-city comparison point; its metrics must not be merged with single-flow CityFlow results.",
        "limitation": "Cross-city gains may come from representation and online adaptation, not world-model prediction.",
        "traffic_inspiration": "A future heterogeneous pretraining claim must compare against CrossLight/X-Light rather than only single-city controllers.",
        "evidence_pointer": "paper Abstract and Sec. 3-5; KDD DOI 10.1145/3637528.3671927",
    },
    {
        "paper_id": "D17",
        "title": "Multi-Agent Reinforcement Learning for Traffic Signal Control through Universal Communication Method",
        "year": "2022",
        "venue": "IJCAI 2022",
        "publication_status": "formal_main_track",
        "layer": "multi_agent_tsc;neighbor_impact",
        "formal_url": "https://www.ijcai.org/proceedings/2022/535",
        "pdf_url": "https://www.ijcai.org/proceedings/2022/0535.pdf",
        "code_url": "https://github.com/zyr17/UniLight",
        "license": "MIT",
        "stars": "39",
        "motivation": "Communicate information that is important to neighboring intersections rather than sharing observations heuristically.",
        "state_action": "Lane flow, green/phase features, road relations, and local discrete phase actions.",
        "prediction_targets": "Predict phase impact and outgoing road volumes that become neighbor inputs.",
        "training_horizon": "Auxiliary one-step phase/volume prediction losses are trained with DQN control.",
        "planning": "DQN chooses phases; predictions form communication features rather than a candidate MPC score.",
        "uncertainty_safety": "No ensemble or conservative fallback.",
        "protocol_baselines": "CityFlow Jinan, Hangzhou, New York, and two Shanghai datasets; the repository warns its CityFlow travel-time definition differs from upstream.",
        "result_summary": "The official IJCAI page reports universal gains when UniComm is added to existing methods and stronger UniLight performance.",
        "limitation": "Repository metric semantics differ from upstream CityFlow and outputs are not conditioned on all neighbors' simultaneous selected actions.",
        "traffic_inspiration": "Predict movement-level outgoing volumes and route them along road relations; preserve our simulator's metric contract.",
        "evidence_pointer": "official IJCAI page; rl/models/innerModels/NewModel.py:8-78 and rl/agents/NewModelAgent.py:61-153",
    },
    {
        "paper_id": "D18",
        "title": "MaCAR: Urban Traffic Light Control via Active Multi-Agent Communication and Action Rectification",
        "year": "2020",
        "venue": "IJCAI 2020",
        "publication_status": "formal_main_track",
        "layer": "multi_agent_tsc;joint_action",
        "formal_url": "https://www.ijcai.org/proceedings/2020/345",
        "pdf_url": "https://www.ijcai.org/proceedings/2020/0345.pdf",
        "code_url": "not_confirmed",
        "license": "not_confirmed",
        "stars": "not_queried",
        "motivation": "Independent synchronous intersection actions can conflict and bias local action values.",
        "state_action": "Multi-intersection observations and synchronous joint traffic-light actions.",
        "prediction_targets": "Traffic after agents' synchronous actions and corresponding action values.",
        "training_horizon": "Traffic forecasting and action-value rectification are coupled to multi-agent RL training.",
        "planning": "Predictions rectify future actions instead of running a standalone world-model MPC.",
        "uncertainty_safety": "No explicit epistemic uncertainty or fallback.",
        "protocol_baselines": "Synthetic and real-world TSC datasets against contemporary multi-agent TSC baselines.",
        "result_summary": "The official IJCAI page reports improvement over state-of-the-art methods in its protocol.",
        "limitation": "The method corrects learned action values; it does not isolate multi-step model ranking versus MaxPressure.",
        "traffic_inspiration": "Strongest direct precedent for explicitly conditioning traffic predictions on synchronous neighboring actions.",
        "evidence_pointer": "official IJCAI page Abstract; paper Sec. 3-5",
    },
    {
        "paper_id": "D19",
        "title": "GPLight: Grouped Multi-Agent Reinforcement Learning for Large-Scale Traffic Signal Control",
        "year": "2023",
        "venue": "IJCAI 2023",
        "publication_status": "formal_main_track",
        "layer": "multi_agent_tsc;large_scale",
        "formal_url": "https://www.ijcai.org/proceedings/2023/23",
        "pdf_url": "https://www.ijcai.org/proceedings/2023/0023.pdf",
        "code_url": "not_confirmed",
        "license": "not_confirmed",
        "stars": "not_queried",
        "motivation": "Balance per-intersection heterogeneity against parameter and optimization cost in large networks.",
        "state_action": "Real-time flow and fine-grained road topology define dynamically learned intersection groups.",
        "prediction_targets": "Group assignments and group-shared value/control representations, not environment transitions.",
        "training_horizon": "End-to-end MARL with mutual-information and group-separation objectives.",
        "planning": "QMIX-style grouped policy learning.",
        "uncertainty_safety": "No world-model uncertainty or fallback.",
        "protocol_baselines": "Synthetic and real networks up to 1,089 intersections; baselines include FixedTime, MaxPressure, IntelliLight, CoLight, and MPLight.",
        "result_summary": "Table 3 reports 735.51 s on Grid33x33-Bi versus 2171.13 for MaxPressure, but this large-network protocol is not directly comparable to our Jinan run.",
        "limitation": "The gain is a controller/grouping result, not evidence for learned dynamics; scale and metric definitions must be replicated before numeric comparison.",
        "traffic_inspiration": "Use as a strong large-network RL boundary and as evidence that static parameter sharing may miss intersection heterogeneity.",
        "evidence_pointer": "paper Sec. 5, Fig. 7, Tables 3-4; official IJCAI page",
    },
    {
        "paper_id": "D20",
        "title": "PressLight: Learning Max Pressure Control to Coordinate Traffic Signals in Arterial Network",
        "year": "2019",
        "venue": "KDD 2019",
        "publication_status": "formal_main_track",
        "layer": "strong_baseline;pressure_rl",
        "formal_url": "https://doi.org/10.1145/3292500.3330949",
        "pdf_url": "author_or_acm_copy",
        "code_url": "https://github.com/wingsweihua/presslight",
        "license": "not_reaudited",
        "stars": "not_queried",
        "motivation": "Tie RL state/reward design to max-pressure traffic theory rather than ad-hoc reward engineering.",
        "state_action": "Lane pressure/queue information and discrete signal phases.",
        "prediction_targets": "Action values and cumulative pressure-based reward; no environment transition model.",
        "training_horizon": "Model-free value learning over simulator interactions.",
        "planning": "Greedy phase selection from learned Q values.",
        "uncertainty_safety": "No learned-model uncertainty; pressure semantics provide the domain prior.",
        "protocol_baselines": "Arterial and network traffic scenarios against transportation and RL baselines.",
        "result_summary": "LibSignal later finds PressLight among the most stable/sample-efficient agents under unified comparisons, reinforcing its baseline role.",
        "limitation": "It does not test a world model, but omitting it would make a new TSC method comparison incomplete.",
        "traffic_inspiration": "Preserve pressure/movement semantics in the model and include PressLight or an equivalent pressure-RL implementation as a strong learned baseline.",
        "evidence_pointer": "KDD paper Sec. 3-5; LibSignal Appendix A.6.1-A.6.4",
    },
    {
        "paper_id": "D21",
        "title": "CoLight: Learning Network-Level Cooperation for Traffic Signal Control",
        "year": "2019",
        "venue": "CIKM 2019",
        "publication_status": "formal_main_track",
        "layer": "strong_baseline;graph_coordination",
        "formal_url": "https://doi.org/10.1145/3357384.3357902",
        "pdf_url": "author_or_acm_copy",
        "code_url": "https://github.com/wingsweihua/colight",
        "license": "not_reaudited",
        "stars": "not_queried",
        "motivation": "Learn network-level coordination by selecting influential neighboring intersections.",
        "state_action": "Per-intersection traffic features, graph neighbors, and discrete phases.",
        "prediction_targets": "Graph-attention features and Q values, not next traffic state.",
        "training_horizon": "Model-free multi-agent value learning.",
        "planning": "Learned per-intersection decisions with graph attention.",
        "uncertainty_safety": "No world-model uncertainty or fallback.",
        "protocol_baselines": "Multiple synthetic and real traffic networks; reimplemented in LibSignal for cross-simulator comparison.",
        "result_summary": "Formal publication and unified reimplementation make it a graph-coordination baseline, not a source of world-model claims.",
        "limitation": "State communication alone cannot tell whether neighbors' selected actions causally change a candidate rollout.",
        "traffic_inspiration": "Compare action-semantic world models against graph-attention controllers to separate prediction gains from generic graph modeling gains.",
        "evidence_pointer": "CIKM paper Sec. 3-5; LibSignal model/benchmark discussion",
    },
    {
        "paper_id": "D22",
        "title": "GMAN: A Graph Multi-Attention Network for Traffic Prediction",
        "year": "2020",
        "venue": "AAAI 2020",
        "publication_status": "formal_main_track",
        "layer": "graph_dynamics;multi_step_prediction",
        "formal_url": "https://ojs.aaai.org/index.php/AAAI/article/view/5477",
        "pdf_url": "https://ojs.aaai.org/index.php/AAAI/article/download/5477/5333",
        "code_url": "https://github.com/zhengchuanpan/GMAN",
        "license": "Apache-2.0",
        "stars": "539",
        "motivation": "Reduce long-horizon traffic forecasting error caused by complex spatial and temporal dependence.",
        "state_action": "Historical sensor traffic features on a road-network graph; no signal-control action.",
        "prediction_targets": "A direct future sequence of traffic volume or speed using encoder-decoder attention.",
        "training_horizon": "Direct multi-step sequence prediction with transform attention from history to future slots.",
        "planning": "No controller or action-conditioned planning.",
        "uncertainty_safety": "Deterministic predictions; no model-based control safety layer.",
        "protocol_baselines": "Two real-world traffic volume/speed datasets; reports up to 4% MAE improvement at one hour.",
        "result_summary": "The direct future decoder is evidence against assuming recursive one-step rollout is the only multi-step design.",
        "limitation": "Without signal actions, it cannot rank counterfactual phase plans and must not be presented as a World Model controller baseline.",
        "traffic_inspiration": "Test direct 1-5-step prediction as an alternative to recursive rollout, while injecting actions at every future step.",
        "evidence_pointer": "official AAAI page Abstract; paper Fig. 1 and Sec. 3-4",
    },
    {
        "paper_id": "D23",
        "title": "STDEN: Towards Physics-Guided Neural Networks for Traffic Flow Prediction",
        "year": "2022",
        "venue": "AAAI 2022",
        "publication_status": "formal_main_track",
        "layer": "graph_dynamics;physics_prior",
        "formal_url": "https://ojs.aaai.org/index.php/AAAI/article/view/20322",
        "pdf_url": "https://cdn.aaai.org/ojs/20322/20322-13-24335-1-2-20220628.pdf",
        "code_url": "not_confirmed",
        "license": "not_confirmed",
        "stars": "not_queried",
        "motivation": "Combine data-driven traffic prediction with a physically interpretable traffic-flow mechanism.",
        "state_action": "Historical traffic flows on a road graph; no signal action.",
        "prediction_targets": "Future flow generated through a latent potential-energy differential equation network.",
        "training_horizon": "Spatio-temporal flow prediction trained on real Beijing traffic datasets.",
        "planning": "No control or candidate evaluation.",
        "uncertainty_safety": "Physics prior supports interpretation but does not quantify epistemic uncertainty.",
        "protocol_baselines": "Three Beijing datasets against traffic forecasting baselines plus a physical-meaning case study.",
        "result_summary": "The official AAAI page reports stronger forecasting and an interpretable case study.",
        "limitation": "The latent potential formulation is not directly linked to CityFlow movement conservation under changing phases.",
        "traffic_inspiration": "Prefer explicit movement inflow/outflow conservation as the smallest traffic prior; only add differential equations if that simpler prior fails.",
        "evidence_pointer": "official AAAI page Abstract; paper Sec. 3-5",
    },
    {
        "paper_id": "D24",
        "title": "UniST: A Prompt-Empowered Universal Model for Urban Spatio-Temporal Prediction",
        "year": "2024",
        "venue": "KDD 2024",
        "publication_status": "formal_main_track",
        "layer": "cross_city;spatiotemporal_pretraining",
        "formal_url": "https://doi.org/10.1145/3637528.3671662",
        "pdf_url": "https://fi.ee.tsinghua.edu.cn/~dingjingtao/papers/UniST-KDD24.pdf",
        "code_url": "https://github.com/tsinghua-fib-lab/UniST",
        "license": "NOASSERTION",
        "stars": "228",
        "motivation": "Learn a universal urban spatio-temporal predictor across cities, domains, and data-scarce scenarios.",
        "state_action": "Grid or graph spatio-temporal observations across more than 20 scenarios; no control action.",
        "prediction_targets": "Future spatio-temporal fields through masked pretraining and knowledge-guided prompt tuning.",
        "training_horizon": "Large-scale pretraining followed by scenario-specific prompt tuning, including few-shot and zero-shot protocols.",
        "planning": "No TSC controller or action-conditioned MPC.",
        "uncertainty_safety": "No conservative control gate.",
        "protocol_baselines": "More than 20 urban spatio-temporal scenarios with full-data, few-shot, and zero-shot prediction comparisons.",
        "result_summary": "Formal KDD evidence supports heterogeneous pretraining for prediction, not automatically for control.",
        "limitation": "Repository declares no license and its input/output formats do not represent phase-conditioned counterfactual dynamics.",
        "traffic_inspiration": "Use schema masks and shared pretraining only after adding action/movement tokens and evaluating control ranking, not just forecast MAE.",
        "evidence_pointer": "KDD paper Abstract and Sec. 3-5; repository README pretraining/prompt-tuning protocol",
    },
    {
        "paper_id": "D25",
        "title": "Libsignal: An Open Library for Traffic Signal Control",
        "year": "2024",
        "venue": "Machine Learning 113",
        "publication_status": "formal_journal",
        "layer": "benchmark;strong_baseline",
        "formal_url": "https://link.springer.com/article/10.1007/s10994-023-06412-y",
        "pdf_url": "subscription_or_author_copy",
        "code_url": "https://github.com/DaRL-LibSignal/LibSignal",
        "license": "GPL-3.0",
        "stars": "not_queried",
        "motivation": "Make TSC comparisons fair across algorithms, datasets, and CityFlow/SUMO simulators.",
        "state_action": "Unified World/Intersection/Generator interfaces expose lane counts, waiting, pressure, phase, and heterogeneous action spaces.",
        "prediction_targets": "Benchmark infrastructure, not a learned environment model.",
        "training_horizon": "Unified training/evaluation interfaces with cross-simulator calibration and recorded hyperparameters.",
        "planning": "Supports multiple fixed, heuristic, value-based, and policy-gradient agents.",
        "uncertainty_safety": "Not applicable; its value is evaluation semantics and reproducibility.",
        "protocol_baselines": "CityFlow and SUMO, nine calibrated datasets, model reimplementations, standard deviations, and convergence comparisons.",
        "result_summary": "The appendix reports PressLight and IDQN as stable/sample-efficient in many settings and warns actor-critic methods can be much harder to converge on large networks.",
        "limitation": "A library benchmark does not remove differences in phase definitions, flow files, reward, or simulator forks; each comparison contract still needs validation.",
        "traffic_inspiration": "Adopt its baseline/evaluation discipline and preserve exact metric semantics; do not copy GPL code into an MIT project.",
        "evidence_pointer": "official journal lines 38-40,122-128,245-326; Appendix A.2-A.8",
    },
    {
        "paper_id": "D26",
        "title": "Diagnosing Reinforcement Learning for Traffic Signal Control",
        "year": "2019",
        "venue": "arXiv:1905.04716",
        "publication_status": "preprint",
        "layer": "negative_or_risk;state_reward_design",
        "formal_url": "https://arxiv.org/abs/1905.04716",
        "pdf_url": "https://arxiv.org/pdf/1905.04716",
        "code_url": "not_confirmed",
        "license": "not_confirmed",
        "stars": "not_queried",
        "motivation": "Question whether complicated RL states and ad-hoc rewards actually optimize travel time.",
        "state_action": "Concise traffic state and pressure-related reward grounded in classical traffic theory.",
        "prediction_targets": "Model-free action values; no learned transition model.",
        "training_horizon": "RL training evaluated on synthetic and real traffic datasets.",
        "planning": "Learned traffic-light policy.",
        "uncertainty_safety": "No world-model uncertainty; the risk lesson is representation/reward mismatch.",
        "protocol_baselines": "Synthetic and real TSC datasets against contemporary methods, with targeted state/reward analysis.",
        "result_summary": "The paper argues that simpler theory-grounded state/reward design can outperform more complex choices.",
        "limitation": "It is a preprint and does not test multi-step learned dynamics, but it is an important falsifier of complexity-for-complexity's-sake.",
        "traffic_inspiration": "Any World Model gain must survive a strong pressure representation and cannot be attributed only to a larger network.",
        "evidence_pointer": "arXiv Abstract and Sec. 3-5",
    },
]


CODE_AUDITS = [
    {
        "repository": "nicklashansen/tdmpc2",
        "paper_id": "D01",
        "audited_commit": "e9f59321933cbc8e11a002b842adc7d4ffae8ff1",
        "default_branch": "main",
        "stars_query_date": QUERY_DATE,
        "stars": "921",
        "license": "MIT",
        "trajectory_data": "Replay buffer samples fixed-horizon observation, action, reward, termination and optional task sequences; action dimensions are masked by task.",
        "model_io": "Encoder maps observations to latent z; dynamics(z,a)->z'; reward(z,a); termination(z); policy prior(z); ensemble Q(z,a).",
        "action_and_neighbors": "Action is concatenated before dynamics/reward. There is no graph-neighbor concept; continuous multitask action dimensions are padded and masked.",
        "multi_step_objective": "Recursive latent rollout with consistency, reward, termination and Q losses; each step weighted by rho^t.",
        "planner": "Policy-prior trajectories plus Gaussian samples, elite weighting, iterative mean/std updates, terminal Q; receding horizon.",
        "uncertainty_ood_fallback": "Multiple Q heads with min/average aggregation; no dynamics ensemble, support detector, or external safe-controller fallback.",
        "data_leakage_check": "Repository separates online replay sampling from evaluation, but no CityFlow flow-file split semantics exist; must not import its protocol blindly.",
        "key_files": "tdmpc2/common/world_model.py:26-30,114-215 | tdmpc2/tdmpc2.py:123-203,242-316",
        "current_mapping": "src/cityflow_tsc/world_model/model.py:65-77,159-205 | training.py:42-67 | policy.py:76-155",
        "required_interface_change": "Trajectory dataset must return H-step sequences/termination; model adds value/termination heads; planner accepts a terminal-value score. Discrete action masks remain environment-owned.",
        "reuse_boundary": "Safe to adapt MIT design/code patterns with attribution; continuous MPPI and task action masks require reimplementation for discrete phases.",
        "reproduction_risk": "medium: modern maintained code, but JAX-free PyTorch project and discrete graph actions differ materially.",
    },
    {
        "repository": "danijar/dreamerv3",
        "paper_id": "D02",
        "audited_commit": "e3f02248693a79dc8b0ebd62c93683888ddaccfe",
        "default_branch": "main",
        "stars_query_date": QUERY_DATE,
        "stars": "3657",
        "license": "MIT",
        "trajectory_data": "Sequence replay includes observations, previous actions, rewards, is_first/is_last/is_terminal flags and configurable replay context.",
        "model_io": "Recurrent latent dynamics plus observation decoders, reward and continuation heads; actor and distributional value/slow-value heads train on imagined features.",
        "action_and_neighbors": "Previous action conditions recurrent dynamics. No explicit road graph, phase-movement mask, or synchronous neighbor-action message.",
        "multi_step_objective": "Sequence representation/dynamics/reconstruction losses plus imagined actor-critic returns and value bootstrapping.",
        "planner": "Execution samples the actor directly; imagination trains actor/critic offline from model states rather than enumerating candidates at each decision.",
        "uncertainty_ood_fallback": "KL/free-bit/unimix and distributional value improve robustness; no epistemic ensemble, data-support gate, or MaxPressure fallback.",
        "data_leakage_check": "Generic environment replay does not define independent city/flow splits; a TSC adoption must add those contracts.",
        "key_files": "dreamerv3/agent.py:115-244,382-482 | embodied/core/replay.py",
        "current_mapping": "training.py and model.py would both change; current online candidate API in policy.py is a different control paradigm.",
        "required_interface_change": "Would require latent recurrent state, sequence replay, actor/critic checkpoints, and a different execution policy; this exceeds the minimal hypothesis.",
        "reuse_boundary": "MIT permits adaptation, but no code should be copied for the first experiment because wholesale Dreamer migration changes the research question.",
        "reproduction_risk": "high for this project: JAX stack, large architectural delta, and weak causal attribution if performance changes.",
    },
    {
        "repository": "thuml/TrajWorld",
        "paper_id": "D03",
        "audited_commit": "575d9efb1a0fe84e5c91add969b8d32c1bfcd505",
        "default_branch": "main",
        "stars_query_date": QUERY_DATE,
        "stars": "19",
        "license": "NOASSERTION",
        "trajectory_data": "HistoryData/MixDataLoader build padded history windows across datasets; observation/action indicator and variable masks distinguish heterogeneous schemas.",
        "model_io": "Transformer receives histories containing observation, reward and action variables; distributional outputs decode next observation/reward, with task-specific termination functions.",
        "action_and_neighbors": "Actions occupy explicit trajectory variables at each time. No native intersection graph or phase semantics; road topology would need new tokens/masks.",
        "multi_step_objective": "Autoregressive transformer loss over padded trajectory windows; masking objectives support heterogeneous pretraining.",
        "planner": "MPC rolls the transformer with candidate action sequences; actor proposals/noise can generate candidates.",
        "uncertainty_ood_fallback": "Entropy, max entropy, confidence, predictive std or kNN distance can penalize rewards; no calibrated traffic fallback.",
        "data_leakage_check": "Has explicit train/holdout/test arrays in dynamics training, but task and dataset split construction must be audited for any future TSC pretraining.",
        "key_files": "data/history_data.py | data/mix_dataloader.py | dynamics/trajworld_dynamics.py:91-371,375-515 | mpc/mpc.py:54-126,201-231",
        "current_mapping": "data.py future heterogeneous trajectory schema | model.py alternative sequence model | policy.py candidate interface",
        "required_interface_change": "Add roadnet/intersection/feature indicators, padded action masks, history windows and per-flow split metadata; keep CityFlow metric schema unchanged.",
        "reuse_boundary": "No license is declared: design-only inspiration; no implementation copying.",
        "reproduction_risk": "high: JAX stack, missing license, hard-coded paths in MPC examples, and continuous-action assumptions.",
    },
    {
        "repository": "siddarth-c/KDD23-ADAC",
        "paper_id": "D10",
        "audited_commit": "69df9fce98d1295598c2059247f610881c9a3741",
        "default_branch": "main",
        "stars_query_date": QUERY_DATE,
        "stars": "0",
        "license": "NOASSERTION",
        "trajectory_data": "Separate NumPy arrays store state, action, next_state, reward and not_done from a cyclic behavior policy; code converts the entire buffer to a dataframe.",
        "model_io": "Non-neural action-specific nearest-neighbor finite MDP over core states; outputs sparse transition matrices and pessimistically shaped rewards.",
        "action_and_neighbors": "Discrete action indexes partition neighbor search. Large multi-intersection state may be flattened; no explicit graph joint-action factorization.",
        "multi_step_objective": "No neural multi-step loss; value iteration solves the inferred finite MDP.",
        "planner": "Solved policy lookup for core states and neighbor-weighted action values for unseen states.",
        "uncertainty_ood_fallback": "State distance to logged action-conditioned neighbors drives fixed/adaptive reward cost; no ensemble or external controller fallback.",
        "data_leakage_check": "Offline buffer generation/evaluation scripts are separate, but repository does not encode our held-out-flow manifest requirements.",
        "key_files": "ADAC/dac_mdp.py:141-252,273-338,412-502 | ADAC/main.py:15-115",
        "current_mapping": "policy.py advantage/support gate and data.py coverage diagnostics; not a replacement for GraphWorldModel.",
        "required_interface_change": "Compute candidate support distance or density from training trajectories and expose it to planner scoring; calibration split must remain flow-disjoint.",
        "reuse_boundary": "No declared license: mechanism description only; implement independently.",
        "reproduction_risk": "high: old environment, bundled binary/data artifacts, absent license, and algorithm differs from neural rollout.",
    },
    {
        "repository": "CMACH508/CausalExploration",
        "paper_id": "D11",
        "audited_commit": "9d166091b183f28deb708c94317705892e6b9cff",
        "default_branch": "main",
        "stars_query_date": QUERY_DATE,
        "stars": "8",
        "license": "NOASSERTION",
        "trajectory_data": "Small online ring buffer stores concatenated state-action input and next state; traffic example is a single SUMO intersection.",
        "model_io": "One Keras MLP per next-state factor; a causal adjacency row masks the state-action inputs for that factor.",
        "action_and_neighbors": "Traffic action is binary switch/stay; there is no multi-intersection neighbor action. Structural mask is learned/updated by causal discovery.",
        "multi_step_objective": "One-step factorwise MSE; model error becomes an exploration reward.",
        "planner": "Exploration policy seeks data useful for world-model learning; no deployment MPC.",
        "uncertainty_ood_fallback": "Prediction error/surprise guides exploration, not calibrated uncertainty or safe fallback.",
        "data_leakage_check": "Online discovery/training intertwines collection and model updates by design; not suitable as-is for fixed offline held-out evaluation.",
        "key_files": "traffic/models/CausalWorldModel.py:9-92 | traffic/algorithms/explore_agent.py | traffic/exploration.py",
        "current_mapping": "model.py transition input mask using known phase_movement_mask; data collection changes are not required for the first test.",
        "required_interface_change": "Pass phase_movement_mask into model forward and derive deterministic action-to-movement gates; do not add causal discovery until known topology is exhausted.",
        "reuse_boundary": "No declared license and legacy Keras: design-only inspiration.",
        "reproduction_risk": "high: single-intersection action semantics, old TensorFlow/Keras, causal assumptions, and no controller comparison to MaxPressure.",
    },
    {
        "repository": "RL-DLMU/PRLight-and-PLight",
        "paper_id": "D12",
        "audited_commit": "3fc3eda93698d7ec4f39cbd553821ea761460b23",
        "default_branch": "main",
        "stars_query_date": QUERY_DATE,
        "stars": "0",
        "license": "NOASSERTION",
        "trajectory_data": "CityFlow datasets include multiple Jinan, Hangzhou and New York flow files; custom buffers support multi-agent training and source-policy pools.",
        "model_io": "Graph-attention encoder processes observations/adjacency; decoder concatenates encoded node state with action to predict next observation; Q head shares encoder.",
        "action_and_neighbors": "Local action is explicit in decoder and neighbor observations enter attention. Inspected decoder does not explicitly receive every neighbor's simultaneously selected action.",
        "multi_step_objective": "One-step environmental prediction jointly trained with Q learning; policy reuse selects source agents by target similarity.",
        "planner": "Q-policy with source-policy reuse; no online model rollout search.",
        "uncertainty_ood_fallback": "Similarity-based source selection, no ensemble calibration or MaxPressure fallback.",
        "data_leakage_check": "Multiple named flow files exist, but train/selection/test use must be checked before adopting numbers; similarity selection can leak target information if not nested correctly.",
        "key_files": "PLight/EDQN.py:20-137 | PRLight/EDQN.py:20-157 | PRLight/avg-Encoder.py | data/* flow files",
        "current_mapping": "model.py action-conditioned graph dynamics; train_world_model.py flow-split experiment orchestration; future pretraining only.",
        "required_interface_change": "Add explicit neighbor-action message and flow-split metadata; if policy reuse is tested, source selection must use adaptation data only, never held-out metrics.",
        "reuse_boundary": "No declared license: design-only inspiration and independent implementation.",
        "reproduction_risk": "high: sparse documentation, generated artifacts in repo, unclear split semantics, and no license.",
    },
    {
        "repository": "zyr17/UniLight",
        "paper_id": "D17",
        "audited_commit": "ead88399d04889fa3631e0f3326e4636bf7d4d84",
        "default_branch": "master",
        "stars_query_date": QUERY_DATE,
        "stars": "39",
        "license": "MIT",
        "trajectory_data": "CityFlow environment produces lane flows/green/phase, road relations, and next-in-lane vehicle targets for Jinan, Hangzhou, New York and Shanghai datasets.",
        "model_io": "PhasePredict produces phase-impact features; VolumePredict maps lane embeddings and phase to outgoing road volumes; predicted incoming volume augments DQN state.",
        "action_and_neighbors": "Road relations route outgoing predictions to neighbor incoming lanes. Neighbor selected actions are not passed jointly into one environmental dynamics step.",
        "multi_step_objective": "One-step phase BCE and volume MSE auxiliary losses alongside DQN loss.",
        "planner": "DQN/dueling DQN control, not model rollout planning.",
        "uncertainty_ood_fallback": "No ensemble/OOD/fallback in the inspected path.",
        "data_leakage_check": "Repository warns its forked CityFlow changes average-travel-time computation; its raw numbers are not directly comparable with upstream CityFlow.",
        "key_files": "rl/models/innerModels/NewModel.py:8-189 | rl/agents/NewModelAgent.py:61-223 | README metric warning",
        "current_mapping": "model.py movement-level transition head and topology buffers; policy.py needs joint neighbor actions only if dynamics gains are established.",
        "required_interface_change": "Represent per-phase permitted movements and aggregate predicted outflow along exact road/movement mappings; preserve our simulator and metric definition.",
        "reuse_boundary": "MIT allows adaptation with attribution; reimplement tensor shapes because environment schema and CityFlow fork differ.",
        "reproduction_risk": "medium-high: Python 3.6-era stack and custom simulator metric semantics despite available code/license.",
    },
    {
        "repository": "XingshuaiHuang/ModelLight",
        "paper_id": "D13",
        "audited_commit": "76686a2791dc15b936c7713765776e5f09c46f15",
        "default_branch": "main",
        "stars_query_date": QUERY_DATE,
        "stars": "10",
        "license": "MIT",
        "trajectory_data": "BatchEpisodes store local observation, action, next observation and reward; repo includes multiple city scenarios and generated flow files.",
        "model_io": "GP/ANN/LSTM takes lane vehicle counts concatenated with an explicit phase vector and predicts next lane counts plus reward.",
        "action_and_neighbors": "Action is converted to its phase-lane vector before prediction. Model is local and has no explicit graph-neighbor action input.",
        "multi_step_objective": "One-step supervised MSE; recursive imaginary transitions are generated for meta-RL updates.",
        "planner": "Imagined data train/adapt a Q controller; no online MPC candidate ranking.",
        "uncertainty_ood_fallback": "GP option may yield uncertainty conceptually, but inspected controller path has no calibrated ensemble penalty or rule fallback.",
        "data_leakage_check": "Random validation samples are drawn from transitions outside the training slice, but repository does not enforce city/flow-disjoint splits for our claim.",
        "key_files": "intersection_model.py:21-99,123-216 | metalearner.py:64-169 | agent.py:195-248",
        "current_mapping": "model.py action embedding must be augmented by phase_movement_mask; training.py multi-step sequence loss; no public API change during research.",
        "required_interface_change": "Pass phase_movement_mask to the model/checkpoint and gate movement deltas by selected phase; add H-step training before recursive rollout claims.",
        "reuse_boundary": "MIT allows adaptation with attribution; legacy TensorFlow code should not be copied into the PyTorch core.",
        "reproduction_risk": "medium-high: preprint-only venue status, old TF/Keras, local model, and recursive synthetic-data error.",
    },
]


def write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, str]]) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=fieldnames,
            extrasaction="ignore",
            lineterminator="\n",
        )
        writer.writeheader()
        writer.writerows(rows)


def normalize_title(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", " ", value.lower()).strip()


def build_master() -> None:
    fields = [
        "paper_id", "title", "year", "venue", "publication_type",
        "publication_status", "layers", "source_queries", "best_search_rank",
        "authors", "doi", "primary_url", "cited_by_count", "open_access",
        "code_url", "official_code", "stars_query_date", "stars", "license",
        "simulator", "datasets", "protocol", "baselines", "metrics",
        "seeds_variance", "state_action", "prediction_target",
        "multi_step_training", "reward_head", "termination_head", "value_head",
        "planning", "uncertainty", "migration_target", "evidence_status",
        "triage_status", "notes",
    ]
    selected_titles = {normalize_title(paper["title"]) for paper in PAPERS}
    rows = []
    with (ROOT / "deduped_papers.csv").open(newline="", encoding="utf-8") as handle:
        for item in csv.DictReader(handle):
            if normalize_title(item["title"]) in selected_titles:
                continue
            row = {field: item.get(field, "not_extracted") for field in fields}
            row.update(
                publication_status=item.get("publication_status") or "candidate_unverified",
                layers=item.get("layers") or "not_extracted",
                primary_url=item.get("primary_url") or "not_extracted",
                state_action="not_extracted",
                prediction_target=item.get("prediction_target") or "not_extracted",
                multi_step_training="not_extracted",
                reward_head="not_extracted",
                termination_head="not_extracted",
                value_head="not_extracted",
                planning=item.get("planning") or "not_extracted",
                uncertainty=item.get("uncertainty") or "not_extracted",
                migration_target=item.get("migration_target") or "not_extracted",
                evidence_status="indirect_discovery_metadata",
                triage_status="not_selected_for_deep_read",
                notes="OpenAlex discovery candidate; use reject_reasons.csv and re-admit only after primary-source review.",
            )
            rows.append(row)
    for paper in PAPERS:
        rows.append({
            "paper_id": paper["paper_id"],
            "title": paper["title"],
            "year": paper["year"],
            "venue": paper["venue"],
            "publication_type": "journal_article" if paper["publication_status"] == "formal_journal" else "conference_paper",
            "publication_status": paper["publication_status"],
            "layers": paper["layer"],
            "source_queries": "targeted_primary_source_followup",
            "best_search_rank": "curated",
            "authors": "see_primary_source",
            "doi": paper["formal_url"] if "doi.org" in paper["formal_url"] else "see_primary_source",
            "primary_url": paper["formal_url"],
            "cited_by_count": "not_used_for_admission",
            "open_access": "see_primary_source",
            "code_url": paper["code_url"],
            "official_code": "confirmed" if paper["code_url"].startswith("https://github.com/") else "not_confirmed",
            "stars_query_date": QUERY_DATE if paper["stars"].isdigit() else "not_queried",
            "stars": paper["stars"],
            "license": paper["license"],
            "simulator": "CityFlow_or_SUMO" if "tsc" in paper["layer"] or "traffic" in paper["title"].lower() else "paper_specific",
            "datasets": paper["protocol_baselines"],
            "protocol": paper["protocol_baselines"],
            "baselines": "see paper_evidence.csv and baseline_boundary_matrix.csv",
            "metrics": paper["result_summary"],
            "seeds_variance": "not_safely_extracted_unless_explicit_in_paper_evidence",
            "state_action": paper["state_action"],
            "prediction_target": paper["prediction_targets"],
            "multi_step_training": paper["training_horizon"],
            "reward_head": "see prediction_target",
            "termination_head": "see paper_evidence.csv",
            "value_head": "see paper_evidence.csv",
            "planning": paper["planning"],
            "uncertainty": paper["uncertainty_safety"],
            "migration_target": paper["traffic_inspiration"],
            "evidence_status": "primary_source_reviewed",
            "triage_status": "deep_read_admitted",
            "notes": paper["limitation"],
        })
    rows.sort(key=lambda row: (row["triage_status"] != "deep_read_admitted", -int(row["year"] or 0), row["title"].lower()))
    write_csv(ROOT / "papers_master.csv", fields, rows)


def build_triage() -> None:
    fields = [
        "paper_id", "title", "year", "venue", "publication_status", "layer",
        "triage_status", "admission_reason", "formal_url", "pdf_url", "code_url",
        "license", "stars_query_date", "stars", "evidence_status",
    ]
    rows = []
    for paper in PAPERS:
        row = dict(paper)
        row.update(
            triage_status="deep_read_admitted",
            admission_reason="nearest mechanism, direct TSC evidence, strong baseline, or explicit risk boundary",
            stars_query_date=QUERY_DATE if paper["stars"].isdigit() else "not_queried",
            evidence_status="primary_source_reviewed",
        )
        rows.append(row)
    write_csv(ROOT / "triage.csv", fields, rows)


def build_evidence_and_claims() -> None:
    evidence_fields = [
        "paper_id", "title", "year", "venue", "publication_status", "layer",
        "motivation", "state_action", "prediction_targets", "training_horizon",
        "planning", "uncertainty_safety", "protocol_baselines", "result_summary",
        "limitation", "traffic_inspiration", "evidence_pointer", "formal_url",
        "pdf_url", "code_url", "license", "deep_read_status",
    ]
    evidence_rows = []
    claim_rows = []
    for paper in PAPERS:
        evidence = dict(paper)
        evidence["deep_read_status"] = "complete_primary_source_and_method_path"
        evidence_rows.append(evidence)
        base = paper["paper_id"]
        common = {
            "paper_id": base,
            "supports": "",
            "contradicts": "",
            "related_baseline": "",
            "related_risk": "",
            "related_gap": "",
        }
        claim_rows.extend([
            {
                **common,
                "claim_id": f"{base}-C1",
                "claim_text": paper["state_action"] + " " + paper["prediction_targets"],
                "claim_type": "mechanism",
                "source_level": "direct",
                "evidence_quote_or_pointer": paper["evidence_pointer"],
                "confidence": "0.90",
            },
            {
                **common,
                "claim_id": f"{base}-C2",
                "claim_text": paper["protocol_baselines"],
                "claim_type": "protocol",
                "source_level": "direct",
                "evidence_quote_or_pointer": paper["formal_url"] + " | " + paper["evidence_pointer"],
                "confidence": "0.88",
            },
            {
                **common,
                "claim_id": f"{base}-C3",
                "claim_text": paper["limitation"],
                "claim_type": "limitation",
                "source_level": "inference",
                "evidence_quote_or_pointer": "Inference from admitted mechanism/protocol: " + paper["evidence_pointer"],
                "confidence": "0.80",
            },
        ])
    write_csv(ROOT / "paper_evidence.csv", evidence_fields, evidence_rows)
    claim_fields = [
        "claim_id", "paper_id", "claim_text", "claim_type", "source_level",
        "supports", "contradicts", "related_baseline", "related_risk",
        "related_gap", "evidence_quote_or_pointer", "confidence",
    ]
    write_csv(ROOT / "claims.csv", claim_fields, claim_rows)


def build_rejections() -> None:
    admitted_titles = {paper["title"].lower() for paper in PAPERS}
    rows = []
    with (ROOT / "deduped_papers.csv").open(newline="", encoding="utf-8") as handle:
        for item in csv.DictReader(handle):
            title = item["title"].lower()
            if title in admitted_titles:
                continue
            if any(token in title for token in ("video world model", "driving world model", "autonomous driving")):
                code = "pure_video_or_driving_boundary"
            elif "survey" in title or "review" in title:
                code = "secondary_source_not_deep_set"
            elif any(token in title for token in ("traffic forecast", "traffic flow predict", "traffic prediction")):
                code = "non_action_conditioned_prediction_lower_priority"
            elif any(token in title for token in ("traffic signal", "traffic light", "world model", "model-based reinforcement")):
                code = "relevant_candidate_not_in_26_paper_evidence_core"
            else:
                code = "title_abstract_outside_locked_questions"
            rows.append({
                "paper_id": item["paper_id"],
                "title": item["title"],
                "year": item["year"],
                "source_queries": item["source_queries"],
                "triage_status": "not_selected_for_deep_read",
                "reason_code": code,
                "evidence_status": "discovery_metadata_only",
                "note": "This is a depth-budget decision, not a claim that the paper is invalid; re-admit only with a specific uncovered mechanism or citation edge.",
            })
    write_csv(
        ROOT / "reject_reasons.csv",
        ["paper_id", "title", "year", "source_queries", "triage_status", "reason_code", "evidence_status", "note"],
        rows,
    )


def build_citation_edges() -> None:
    rows = [
        ("D01", "D05", "uncertainty-aware MPC ancestor", "included"),
        ("D01", "D02", "modern world-model control baseline", "included"),
        ("D03", "D07", "offline rollout penalty implementation ancestor", "included"),
        ("D04", "D02", "world-model architecture comparison boundary", "included"),
        ("D07", "D06", "short-rollout policy optimization ancestor", "included"),
        ("D08", "D07", "explicit uncertainty critique", "included"),
        ("D09", "D07", "alternative pessimistic offline model design", "included"),
        ("D10", "D09", "pessimistic MDP ancestor", "included"),
        ("D12", "D13", "direct TSC model-based/meta-learning neighbor", "included"),
        ("D14", "D02", "Dreamer family world-model control ancestor", "included"),
        ("D15", "D16", "recent cross-city comparison neighbor", "included"),
        ("D17", "D18", "neighbor impact versus synchronous action prediction", "included"),
        ("D18", "D21", "graph communication baseline", "included"),
        ("D19", "D20", "pressure baseline", "included"),
        ("D22", "D23", "data-driven versus physics-guided forecasting", "included"),
        ("D24", "D03", "heterogeneous pretraining comparison", "included"),
        ("D25", "D20", "unified benchmark evidence for pressure RL", "included"),
        ("D26", "D20", "state/reward theory boundary", "included"),
    ]
    write_csv(
        ROOT / "citation_edges.csv",
        ["source_paper_id", "neighbor_paper_id", "edge_reason", "admission_status"],
        [dict(zip(["source_paper_id", "neighbor_paper_id", "edge_reason", "admission_status"], row)) for row in rows],
    )
    missed = [
        {
            "candidate": "Trust the Model Where It Trusts Itself: Model-Based Actor-Critic with Uncertainty-Aware Rollout Adaptation",
            "reason_not_deep_read": "ICML 2024 adjacent mechanism; retained for follow-up if ensemble calibration becomes the main method.",
            "coverage": "Adaptive rollout horizon is already bounded by MBPO plus MOPO/COMBO in the current evidence set.",
        },
        {
            "candidate": "DenseLight: Efficient Control for Large-Scale Traffic Signals with Dense Feedback",
            "reason_not_deep_read": "Recent strong TSC controller but not a world-model mechanism.",
            "coverage": "Baseline boundary is already covered by PressLight, CoLight, GPLight, X-Light and LibSignal; add before full paper experiments if implementation is available.",
        },
        {
            "candidate": "Generalized Phase Pressure Control Enhanced Reinforcement Learning for Traffic Signal Control",
            "reason_not_deep_read": "2025 preprint discovered after the core set; formal status not established in this pass.",
            "coverage": "Potentially important pressure baseline; must be rechecked before a venue submission because it may narrow the action-semantics gap.",
        },
    ]
    write_csv(ROOT / "missed_papers.csv", ["candidate", "reason_not_deep_read", "coverage"], missed)


def build_code_audits() -> None:
    fields = [
        "repository", "paper_id", "audited_commit", "default_branch",
        "stars_query_date", "stars", "license", "trajectory_data", "model_io",
        "action_and_neighbors", "multi_step_objective", "planner",
        "uncertainty_ood_fallback", "data_leakage_check", "key_files",
        "current_mapping", "required_interface_change", "reuse_boundary",
        "reproduction_risk", "audit_mode",
    ]
    rows = []
    for audit in CODE_AUDITS:
        row = dict(audit)
        row["audit_mode"] = "static_only_no_install_no_execution"
        rows.append(row)
    write_csv(ROOT / "code_audit_matrix.csv", fields, rows)


def main() -> None:
    build_master()
    build_triage()
    build_evidence_and_claims()
    build_rejections()
    build_citation_edges()
    build_code_audits()
    print(f"wrote curated evidence for {len(PAPERS)} papers")


if __name__ == "__main__":
    main()
